services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: omr_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: omr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da sua API FastAPI
  api:
    build: .
    container_name: omr_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/omr_db
    depends_on:
      - db

volumes:
  postgres_data:

web:
  build: .
  volumes:
    - ./static:/app/static # Persiste as fotos na sua máquina real
  ports:
    - "8000:8000"