services:
  api:
    build: .
    container_name: sistema_omr_api
    ports:
      - "8000:8000"
    shm_size: '1gb'
    volumes:
      - .:/app
      - ./static:/app/static # PersistÃªncia de PDFs e imagens processadas
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/omr_db
      - PYTHONUNBUFFERED=1
      - FLAGS_allocator_strategy=auto_growth
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: sistema_omr_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=omr_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d omr_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: